version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  commit-message:
      prefix: "php packages"
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "github-actions"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: /
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
        
